name: E2E Tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["12.x", "14.x", "16.x"]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Node.JS dependencies
        run: npm install

      - name: Run JavaScript testing suite
        run: npm test
